In [ ]:
import numpy as np
a=[1,2,3,4,5,6]
type(a)
b= np.array(a)
type(b)
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e=np.ones((4,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
r=np.random.rand(3,4)
print(r)

[[0.85594557 0.5834382  0.23247534 0.61122481]
 [0.50647518 0.00348663 0.81278306 0.64559806]
 [0.73681877 0.36091169 0.63632415 0.02452488]]


In [ ]:
n=np.random.randint(1,50, size=(2,2))
print(n)

[[24 16]
 [40 25]]


In [ ]:
r=np.random.choice((2,3,4,5))
print(r)

2


In [44]:
w=np.full((1,2,3,4),(4))
print(w)

[[[[4 4 4 4]
   [4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]
   [4 4 4 4]]]]


In [47]:
j=np.eye(4,k=-2)
print(j)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [50]:
q=np.arange(1,9)
print(q)

[1 2 3 4 5 6 7 8]


In [57]:
m=np.arange(1,20,5)
print(m)

[ 1  6 11 16]


In [62]:
n=np.linspace(1,20,5)
print(n)

[ 1.    5.75 10.5  15.25 20.  ]


In [66]:
a=[1,2,3,4,5,6]
b=np.array(a)
b.ndim


1

In [82]:
a=[1,2,3]
b=[7,8,9]
d=[7,5,4]
c=np.array([a,b,d])
c.ndim
c.shape
c.size

9