In [ ]:
import numpy as np
a = np.array([3,6,9,12,3,5,9,8,7])
print(a)

[ 3  6  9 12  3  5  9  8  7]


In [ ]:
np.reshape(a, (3,3))

array([[ 3,  6,  9],
       [12,  3,  5],
       [ 9,  8,  7]])

In [ ]:
a.reshape(3,3)

array([[ 3,  6,  9],
       [12,  3,  5],
       [ 9,  8,  7]])

In [ ]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
x.size

15

In [ ]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
y = x.reshape(5,3)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
z = np.transpose(y)
print(z)

[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


In [ ]:
y.transpose()

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [ ]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a[2:6]


array([3, 4, 5, 6])

In [ ]:
x = np.arange(1,16).reshape(5,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
x[1,2]

np.int64(6)

In [ ]:
x[1][2]

np.int64(6)

In [ ]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)

[1 2 3 4 5]


In [ ]:
print(b)

[ 6  7  8  9 10]


In [ ]:
x = np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
x = np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])
print(a)

[10 12 14 16 18 20]


In [ ]:
print(b)

[[2]
 [2]]


In [59]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [60]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [61]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [62]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [67]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])