In [4]:
import numpy as np
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [6]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [7]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [8]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [9]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [10]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [11]:
np.tan(a)

array([[1.55740772, 0.        , 0.        , 0.        ],
       [0.        , 1.55740772, 0.        , 0.        ],
       [0.        , 0.        , 1.55740772, 0.        ],
       [0.        , 0.        , 0.        , 1.55740772]])

In [13]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
import math
dtype=int
print(math.sqrt(16))


4.0


In [22]:
a=np.arange(5,15,2)

In [23]:
print(a)

[ 5  7  9 11 13]


In [24]:
np.mean(a)

np.float64(9.0)

In [25]:
np.median(a)

np.float64(9.0)

In [26]:
np.std(a)

np.float64(2.8284271247461903)

In [28]:
a = np.array([[8,4],[2,9]])
print(a)

[[8 4]
 [2 9]]


In [29]:
print(np.min(a, axis = 0))

[2 4]


In [30]:
print(np.min(a, axis = 1))

[4 2]


In [31]:
print(np.max(a,axis=0))

[8 9]


In [34]:
print(np.max(a,axis=1))

[8 9]


In [39]:
n=np.array([1,4,3,10,20])
x=np.sort(a ,kind='merge sort')
print(x)

[[4 8]
 [2 9]]


In [48]:
A = np.arange(10,35).reshape(5,5)
B = np.ones((5,5))
print(A)


[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [46]:
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
np.dot(A,B)

array([[33., 33., 33.],
       [42., 42., 42.],
       [51., 51., 51.]])

In [44]:
A.dot(B)

array([[33., 33., 33.],
       [42., 42., 42.],
       [51., 51., 51.]])